### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by LeDrew2017** [ProjectInfinity-X/official_devices#229]
### Device you want to apply for

Samsung Galaxy S10 series and Samsung Galaxy Note 10 series (exynos9820 common tree)

### Device Tree Sources

https://github.com/orgs/Infinity-X-Project/repositories

### Number of rom(s) you maintain, also name them stating official or unofficial

1 ROM Project Matrixx official

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

https://t.me/FreeRunner4everupdates/555

### Any Exceptions/special concern?

I've been maintaining ROMs for about 3 years or so.
The devices I'll be maintaing are beyond0lte, beyond1lte, beyond2lte,beyondx, d1,d2s,d2x,d1x and f62  all part of a universal tree.

### Telegram username / or any alternative medium to reach you

t.me/FreeRunner4ever

### GitHub username

LeDrew2017

**Comment by tejas101k** [comment]
Hi there, I have checked the resources provided..
It seems fine considering the "Exynos" situation

However some regularities have to be maintained 
https://github.com/Infinity-X-Project/android_device_samsung_beyond0lte/commit/89a880c3b9756c8884f0f86f23588ae5e623fc2c#diff-65803765b59440a7be06b059879f09a5fbca828058d0ecb88a53112bf3ed8684R1
**(This could be kept more professional while applying for OFFICIAL)**

https://github.com/Infinity-X-Project/android_device_samsung_beyond0lte/commit/89a880c3b9756c8884f0f86f23588ae5e623fc2c#diff-65803765b59440a7be06b059879f09a5fbca828058d0ecb88a53112bf3ed8684R5
**(The RAM and ROM props are not supposed to be hardcoded since these are detected automatically for users with different variants)**

Also coming to your platform link provided to reach you, I see your profile picture and other details like bio are not in-par with tying ways from other projects.. We don't have any beef with the project mentioned nor they do.. But still when you're connecting ties from multiple projects, joining the discussion/maintainers group, it is expected to keep an unbiased identity.. Hope you understand.

Please re-ping me if you're fine to follow my recommendations
Thanks

**Comment by tejas101k** [comment]
Accepting since i think you understood what i meant about your platform appearance.. Thanks for it and also remember about the AboutPhone modifications i mentioned above

Please DM (t.me/tejas101k)
